---
- name: Resolve target resources
  ansible.builtin.include_tasks: resources.yaml

- name: Invoke detect function
  ansible.builtin.include_role:
    name: network.base.detect
  vars:
    state: "replaced"
    resources: "{{ detect_bgp_resources }}"
