objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter:
    health_check_view:
      description: Generate the filtered health check dict based on the provided target.
      name: health_check_view
      version_added: 1.0.0
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 8.0.0
