---
- name: Resolve target resources
  ansible.builtin.include_tasks: resources.yaml

- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.remediate
  vars:
    state: "replaced"
    resources: "{{ remediate_bgp_resources }}"
