---
- name: Resolve target resources
  ansible.builtin.include_tasks: includes/resources.yaml

- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    operation: 'persist'
    resources: "{{ bgp_resources }}"
    ignore_empty: "{{ persist_empty | default(true) }}"
