---
- name: Resolve target resources
  ansible.builtin.include_tasks: resources.yaml

- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.persist
  vars:
    resources: "{{ persist_bgp_resources }}"
    ignore_empty: "{{ persist_empty | default(true) }}"
